VERSION := 0.1.0
PREFIX := ovos
# List the sub-folders that contain Dockerfiles here
COMPONENTS := core audio messagebus messagebus-rust gui-websocket phal simple-listener classic-listener dinkum-listener

include ../base.mk
