VERSION := 0.1.0
PREFIX := ovos-skill
# List the sub-folders that contain Dockerfiles here
COMPONENTS := alerts camera date-time duckduckgo \
			  easter-eggs fallback-unknown hello-world \
			  homescreen jokes parrot personal randomness \
			  tunein volume weather wikihow wikipedia \
			  wolfie wordnet

include ../base.mk
