---
x-podman: &podman
  in_pod: false

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m

x-common-environment: &common-environment
  TZ: ${TZ:-UTC}
  HSA_OVERRIDE_GFX_VERSION: 11.0.0  # YMMV - I needed this for AMD Radeon RX 7600 XT


x-stt-base: &stt-base
  <<: *podman
  restart: unless-stopped
  logging: *default-logging
  userns_mode: "keep-id:uid=1000,gid=1000"
  environment:
    <<: *common-environment
  network_mode: host
  # GPU support
 #stdin_open: true
 #tty: true
 #cap_add:
 #  - SYS_PTRACE
 #security_opt:
 #  - seccomp=unconfined
 #group_add:
 #  - video
 #ipc: host
 #devices:
 #  - /dev/kfd
 #  - /dev/dri
  # volumes
  volumes:
    - ${BASE_DIR}/config/mycroft:/home/ovos/.config/mycroft
    - ${BASE_DIR}/data/mycroft:/home/ovos/.local/share/mycroft
    - ${BASE_DIR}/cache/mycroft:/home/ovos/.cache/mycroft
    - ${BASE_DIR}/state/mycroft:/home/ovos/.local/state/mycroft
    - ${BASE_DIR}/tmp:/tmp/mycroft


services:
  ovos_stt_whisper:
    <<: *stt-base
    hostname: ovos_stt_whisper
    image: jarbasai/ovos-stt-server-whisper:0.1.0
    #ports:
    #  - "80:8080"
    # TODO - volume for downloaded models

other:
  ovos_stt_mynorthai:
    <<: *stt-base
    hostname: ovos_stt_mynorthai
    image: jarbasai/ovos-stt-server-mynorthai:latest
    # TODO - volume for downloaded models

  ovos_stt_hitz:
    <<: *stt-base
    hostname: ovos_stt_hitz
    image: jarbasai/ovos-stt-server-hitz:latest
    # TODO - volume for downloaded models

networks:
  ovos-net:
    external: true
