---
x-podman: &podman
  in_pod: false

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "200m"
    max-file: "1"

x-common-environment: &common-environment
  TZ: ${TZ:-UTC}

x-resource-limits: &resource-limits
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 64M

x-base: &base
  <<: [*podman, *resource-limits]
  restart: unless-stopped
  logging: *default-logging
  userns_mode: "keep-id:uid=1000,gid=1000"
  environment:
    <<: *common-environment
  volumes:
    - ${BASE_DIR}/config/mycroft:/home/ovos/.config/mycroft
    - ${BASE_DIR}/data/mycroft:/home/ovos/.local/share/mycroft
   #- ${BASE_DIR}/cache/ovos_gui:/home/ovos/.cache/ovos_gui
    - ${BASE_DIR}/cache/mycroft:/home/ovos/.cache/mycroft
    - ${BASE_DIR}/state/mycroft:/home/ovos/.local/state/mycroft
    - ${BASE_DIR}/tmp:/tmp/mycroft

services:
  ovos_yaml_editor:
    <<: *base
    build:
      context: ./ovos-yaml-editor
      dockerfile: Dockerfile
    container_name: ovos_yaml_editor
    hostname: ovos_yaml_editor
    image: jarbasai/ovos-yaml-editor:latest
    ports:
      - 9200:9200
    environment: # TODO - move to .env file
      EDITOR_USERNAME: admin
      EDITOR_PASSWORD: password

  ovos-skills-config-tool:
    <<: *base
    container_name: ovos-skills-config
    image: ghcr.io/oscillatelabsllc/ovos-skill-config-tool:latest
    ports:
      - 8000:8000
    environment: # TODO - move to .env file
      OVOS_CONFIG_USERNAME: ovos
      OVOS_CONFIG_PASSWORD: ovos

networks:
  ovos-net:
    external: true
