---
x-podman: &podman
  in_pod: false

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "200m"
    max-file: "1"

x-common-environment: &common-environment
  TZ: ${TZ:-UTC}


x-tts-base: &tts-base
  <<: *podman
  restart: unless-stopped
  logging: *default-logging
  userns_mode: "keep-id:uid=1000,gid=1000"
  tty: true
  environment:
    <<: *common-environment
  volumes:
    - ${BASE_DIR}/config/mycroft:/home/ovos/.config/mycroft
    - ${BASE_DIR}/data/mycroft:/home/ovos/.local/share/mycroft
    - ${BASE_DIR}/cache/mycroft:/home/ovos/.cache/mycroft
    - ${BASE_DIR}/state/mycroft:/home/ovos/.local/state/mycroft
    - ${BASE_DIR}/tmp:/tmp/mycroft


services:
  ovos_tts_piper:
    <<: *tts-base
    hostname: ovos_tts_piper
    restart: unless-stopped
    image: jarbasai/ovos-tts-server-piper:0.1.0
    volumes:
      - ${BASE_DIR}/config/mycroft:/home/ovos/.config/mycroft
      - ${BASE_DIR}/data/mycroft:/home/ovos/.local/share/mycroft
      - ${BASE_DIR}/cache/mycroft:/home/ovos/.cache/mycroft
      - ${BASE_DIR}/state/mycroft:/home/ovos/.local/state/mycroft
      - ${BASE_DIR}/tmp:/tmp/mycroft
      - ${BASE_DIR}/data/piper_tts:/home/ovos/.local/share/piper_tts

other:
  ovos_tts_mimic3:
    <<: *tts-base
    hostname: ovos_tts_mimic3
    restart: unless-stopped
    image: jarbasai/ovos-tts-server-mimic3:latest
    ports:
      - "80:9666"

  ovos_tts_mimic:
    <<: *tts-base
    hostname: ovos_tts_mimic
    restart: unless-stopped
    image: jarbasai/ovos-tts-server-mimic:latest
    ports:
      - "80:9666"

  ovos_tts_google_tx:
    <<: *tts-base
    hostname: ovos_tts_google_tx
    restart: unless-stopped
    image: jarbasai/ovos-tts-server-google-tx:latest
    ports:
      - "80:9666"

  ovos_tts_sam:
    <<: *tts-base
    hostname: ovos_tts_sam
    restart: unless-stopped
    image: jarbasai/ovos-tts-server-sam:latest
    ports:
      - "80:9666"

  ovos_tts_matxa:
    <<: *tts-base
    hostname: ovos_tts_matxa
    restart: unless-stopped
    image: jarbasai/ovos-tts-server-matxa:latest
    ports:
      - "80:9666"

  ovos_tts_nos:
    <<: *tts-base
    hostname: ovos_tts_nos
    restart: unless-stopped
    image: jarbasai/ovos-tts-server-nos:latest
    ports:
      - "80:9666"
    volumes:
      - ${BASE_DIR}/config/mycroft:/home/ovos/.config/mycroft
      - ${BASE_DIR}/data/mycroft:/home/ovos/.local/share/mycroft
      - ${BASE_DIR}/cache/mycroft:/home/ovos/.cache/mycroft
      - ${BASE_DIR}/state/mycroft:/home/ovos/.local/state/mycroft
      - ${BASE_DIR}/tmp:/tmp/mycroft
      - ${BASE_DIR}/data/nos_tts_models:/home/ovos/.local/share/nos_tts_models

networks:
  ovos-net:
    external: true
