VERSION := 0.1.0
PREFIX := ovos-tts-server
# List the sub-folders that contain Dockerfiles here
COMPONENTS := cotovia google-tx mimic nos piper sam
# phoonnx # broken due to https://github.com/TigreGotico/phoonnx/issues/98
# matxa mimic3

include ../base.mk
